/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package heavenhostal;

import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Hashim
 */
public class AddCustomer extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomer
     */
    public AddCustomer() {
        initComponents();
        getContentPane().setBackground(Color.YELLOW);
        ButtonGroup group = new ButtonGroup();
        group.add(jobradio);
        group.add(studentradio);
        setSize(570,700);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        MyItemHandler handler1 = new MyItemHandler();
        jobradio.addItemListener(handler1);
        studentradio.addItemListener(handler1);
        MyHandler handler = new MyHandler();
        savebut.addActionListener(handler);
        refreshbut.addActionListener(handler);
        seatercombo.addItemListener(handler1);
        String timeStamp = new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime());
        datetext.setText(timeStamp);
                }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nametext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mobiletext = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cnictext = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        studentradio = new javax.swing.JRadioButton();
        jobradio = new javax.swing.JRadioButton();
        companytext = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        unitext = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addresstext = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        seatercombo = new javax.swing.JComboBox();
        singlecombo = new javax.swing.JComboBox();
        doublecombo = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        securitfeetext = new javax.swing.JTextField();
        savebut = new javax.swing.JButton();
        cancelbut = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        advancefeetext = new javax.swing.JTextField();
        mealcheck = new javax.swing.JCheckBox();
        heatercheck = new javax.swing.JCheckBox();
        coolercheck = new javax.swing.JCheckBox();
        refreshbut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        datetext = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Customer");
        setResizable(false);

        nametext.setBackground(new java.awt.Color(204, 255, 204));
        nametext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nametext.setToolTipText("Enter Name For Example: Muhammad Hashim Shafiq");
        nametext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Name:");

        mobiletext.setBackground(new java.awt.Color(204, 255, 204));
        mobiletext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mobiletext.setToolTipText("Enter Mobile Number. For Example: 03327173300");
        mobiletext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Mobile:");

        cnictext.setBackground(new java.awt.Color(204, 255, 204));
        cnictext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cnictext.setToolTipText("Enter CNIC Number. For Example: 3130156745775");
        cnictext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("CNIC:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Occupation:");

        studentradio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        studentradio.setText("Student");
        studentradio.setOpaque(false);

        jobradio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jobradio.setText("Job");
        jobradio.setOpaque(false);

        companytext.setBackground(new java.awt.Color(204, 255, 204));
        companytext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        companytext.setToolTipText("Enter Company Name. For Example NetSol Inc.");
        companytext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Company:");

        unitext.setBackground(new java.awt.Color(204, 255, 204));
        unitext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        unitext.setToolTipText("Enter University Name. For Example : Comsats Institute of IT");
        unitext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("University:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("---------- Personal Information ----------");

        addresstext.setBackground(new java.awt.Color(204, 255, 204));
        addresstext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addresstext.setToolTipText("Enter Address. For Example. House No 7A Block W satellite Town Khanpur");
        addresstext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Address:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("---------- Room Information ----------");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Room Allocation:");

        seatercombo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        seatercombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double" }));

        singlecombo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        doublecombo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("---------- Payment Information ----------");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Security Fee:");

        securitfeetext.setBackground(new java.awt.Color(204, 255, 204));
        securitfeetext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        securitfeetext.setToolTipText("Security Fee. For Example: 5000");
        securitfeetext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        savebut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        savebut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heavenhostal/confirm.png"))); // NOI18N
        savebut.setText("SAVE");

        cancelbut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cancelbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heavenhostal/cancel.png"))); // NOI18N
        cancelbut.setText("CANCEL");
        cancelbut.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Advance Rent:");

        advancefeetext.setBackground(new java.awt.Color(204, 255, 204));
        advancefeetext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        advancefeetext.setToolTipText("Advance Rent ");
        advancefeetext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mealcheck.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mealcheck.setText("Meal");
        mealcheck.setOpaque(false);

        heatercheck.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        heatercheck.setText("Heater");
        heatercheck.setOpaque(false);

        coolercheck.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        coolercheck.setText("AC/Cooler");
        coolercheck.setOpaque(false);

        refreshbut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        refreshbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heavenhostal/refresh.png"))); // NOI18N
        refreshbut.setText("Refresh");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Date:");

        datetext.setBackground(new java.awt.Color(204, 255, 204));
        datetext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        datetext.setToolTipText("Enter Name For Example: Muhammad Hashim Shafiq");
        datetext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(142, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(securitfeetext, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(advancefeetext, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(mealcheck)
                                            .addGap(61, 61, 61)
                                            .addComponent(heatercheck))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(refreshbut)
                                            .addGap(26, 26, 26)
                                            .addComponent(seatercombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(addresstext, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(nametext, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(mobiletext, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(cnictext, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(31, 31, 31)
                                        .addComponent(studentradio)
                                        .addGap(32, 32, 32)
                                        .addComponent(jobradio))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(companytext, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(unitext, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coolercheck)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(singlecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(doublecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(datetext, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(105, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(savebut)
                .addGap(18, 18, 18)
                .addComponent(cancelbut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelbut, savebut});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(datetext, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(nametext, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mobiletext, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnictext, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentradio)
                    .addComponent(jobradio))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel6))
                    .addComponent(companytext, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel7))
                    .addComponent(unitext, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel9))
                    .addComponent(addresstext, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(refreshbut)
                            .addComponent(seatercombo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heatercheck)
                            .addComponent(mealcheck))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(securitfeetext, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(advancefeetext, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doublecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(singlecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(coolercheck)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelbut)
                    .addComponent(savebut))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {doublecombo, refreshbut, seatercombo, singlecombo});

        nametext.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String occupation;
    
    public class MyItemHandler implements ItemListener{

        @Override
        public void itemStateChanged(ItemEvent e) {
            if(studentradio.isSelected()){
                occupation = "Student";
                companytext.setEnabled(false);
                unitext.setEnabled(true);
                
        }else if(jobradio.isSelected()){
                occupation = "Work";
                companytext.setEnabled(true);
                unitext.setEnabled(false);
        }
            if(seatercombo.getSelectedItem().equals("Single")){
                doublecombo.setEnabled(false);
                singlecombo.setEnabled(true);
            }else{
                singlecombo.setEnabled(false);
                doublecombo.setEnabled(true);
        }
        }
    }
    public class MyHandler implements ActionListener{
        DBConnection dbs = new DBConnection();
        Connection conn = dbs.db();
        
        String university;
        String company;
        @Override
        public void actionPerformed(ActionEvent e) {
            if(e.getActionCommand().equals("SAVE")){
                 if(unitext.isEnabled()){
                    university = unitext.getText();
                    company = "null";
                }else if(companytext.isEnabled()){
                    company = companytext.getText();
                    university = "null";
                }
                 
                 String single;
                 String duble;
                 
                 
                if(nametext.getText().isEmpty() == false && cnictext.getText().isEmpty() == false && mobiletext.getText().isEmpty() == false && addresstext.getText().isEmpty() == false && university.isEmpty() == false && company.isEmpty() == false && occupation.isEmpty() == false ){
                        
                    
                
                    try{
                        Statement stmt = conn.createStatement();
                        String query1;
                        query1 = "Insert into customer values (" + "'" +nametext.getText()+ "','"+cnictext.getText()+"','"+mobiletext.getText()+"','"+occupation+"','"+university+"','"+company+"','"+addresstext.getText()+"')";
                        String query2;
                            if(singlecombo.isEnabled()){
                                single = (String) singlecombo.getSelectedItem();
                                query2 = "update rooms set roomstatus = 'occupied',ownername = '"+nametext.getText()+"', cnic = '"+cnictext.getText()+"' where roomlabel = '"+single+"'";
                            }else{
                                duble = (String) doublecombo.getSelectedItem();
                                query2 = "update rooms set roomstatus = 'occupied',ownername = '"+nametext.getText()+"', cnic = '"+cnictext.getText()+"' where roomlabel = '"+duble+"'";
                            }
                        
                        int result = stmt.executeUpdate(query1);
                        int result1 = stmt.executeUpdate(query2);
                        if(result>0 && result1>0)
                            //System.out.println(query);
                            JOptionPane.showMessageDialog(null, "Data Successfully Saved","INFO", 1);
                
                    }catch(MySQLIntegrityConstraintViolationException ex){
                        JOptionPane.showMessageDialog(null,"Duplicate Entry for CNIC: "+cnictext.getText(),"Error",0);
                    }catch(SQLException | HeadlessException ex){
                        JOptionPane.showMessageDialog(null,"Error Executing the Query","Error", 0);
                }
                }else{
                  JOptionPane.showMessageDialog(null,"Please Fill All the Fields","Error",0);
                
                }
                
            }else if(e.getActionCommand().equals("Refresh")){
                    
                
                try{
                    Statement stmt = conn.createStatement();
                    ResultSet rs = stmt.executeQuery("select * from rooms");
                    while(rs.next()){
                        if(rs.getString(1).startsWith("S") && rs.getString(2).equalsIgnoreCase("available"))
                            singlecombo.addItem(rs.getString(1));
                        
                        else if(rs.getString(1).startsWith("D") && rs.getString(2).equalsIgnoreCase("available"))
                            doublecombo.addItem(rs.getString(1));
                                    
                          }
                        
                        }catch(Exception ex){
                
                            JOptionPane.showMessageDialog(null, "Error Retrieving Room Database", "Error",0);
                }
                refreshbut.setEnabled(false);
            }
        }
    
    
    
    }
    
    private JButton savebutton;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstext;
    private javax.swing.JTextField advancefeetext;
    private javax.swing.JButton cancelbut;
    private javax.swing.JTextField cnictext;
    private javax.swing.JTextField companytext;
    private javax.swing.JCheckBox coolercheck;
    private javax.swing.JTextField datetext;
    private javax.swing.JComboBox doublecombo;
    private javax.swing.JCheckBox heatercheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jobradio;
    private javax.swing.JCheckBox mealcheck;
    private javax.swing.JTextField mobiletext;
    private javax.swing.JTextField nametext;
    private javax.swing.JButton refreshbut;
    private javax.swing.JButton savebut;
    private javax.swing.JComboBox seatercombo;
    private javax.swing.JTextField securitfeetext;
    private javax.swing.JComboBox singlecombo;
    private javax.swing.JRadioButton studentradio;
    private javax.swing.JTextField unitext;
    // End of variables declaration//GEN-END:variables
}
