/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package heavenhostal;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hashim
 */
public class ListAllCustomer extends javax.swing.JFrame {

    /**
     * Creates new form ListAllCustomer
     */
    public ListAllCustomer() {
        initComponents();
        setSize(775,450);
        setResizable(false);
        getContentPane().setBackground(Color.YELLOW);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("listuser.png")));
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        MyHandler handler = new MyHandler();
        listbut.addActionListener(handler);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        listbut = new javax.swing.JButton();
        cancelbut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("List All Customers");
        setIconImages(null);

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "CNIC", "Mobile", "Occupation", "University", "Company", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        listbut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        listbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heavenhostal/listuser.png"))); // NOI18N
        listbut.setText("List All");

        cancelbut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cancelbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heavenhostal/cancel.png"))); // NOI18N
        cancelbut.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(listbut, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelbut, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listbut)
                    .addComponent(cancelbut))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   public class MyHandler implements ActionListener{
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        DBConnection dbs = new DBConnection();
        Connection conn = dbs.db();
        @Override
        public void actionPerformed(ActionEvent e) {
            
            if(e.getActionCommand().equals("List All")){
                int counter = model.getRowCount();
                
                for(int i =counter-1;i>=0;i-- ){
                    model.removeRow(i);
                }
                
                
                try{
                    Statement stmt = conn.createStatement();
                    String query = "select * from customer";
                    ResultSet rs = stmt.executeQuery(query);
                    while(rs.next()){
                        String[] st = new String[8];
                        st[0] = rs.getString(1);
                        st[1] = rs.getString(2);
                        st[2] = rs.getString(3);
                        st[3] = rs.getString(4);
                        st[4] = rs.getString(5);
                        st[5] = rs.getString(6);
                        st[6] = rs.getString(7);
                        
                        
                        

                        model.addRow(st);
                    }
                }catch(Exception ex){
                
                
                }
            
            }
        }
   
   
   } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbut;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton listbut;
    // End of variables declaration//GEN-END:variables
}
