/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package heavenhostal;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hashim
 */
public class SearchCustomer extends javax.swing.JFrame {

    /**
     * Creates new form SearchCustomer
     */
    public SearchCustomer() {
        initComponents();
        setSize(695,515);
        setResizable(false);
        getContentPane().setBackground(Color.YELLOW);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("searchuser.png")));
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        MyHandler handler = new MyHandler();
        MyItemHandler itemhandler = new MyItemHandler();
        refreshbut.addActionListener(handler);
        searchbut.addActionListener(handler);
        nameradio.addItemListener(itemhandler);
        cnicradio.addItemListener(itemhandler);
        roomradio.addItemListener(itemhandler);
        nameradio.setSelected(true);
        cnictext.setEnabled(false);
        refreshbut.setEnabled(false);
        roomcombo.setEnabled(false);
        
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        nameradio = new javax.swing.JRadioButton();
        cnicradio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        roomradio = new javax.swing.JRadioButton();
        nametext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cnictext = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        refreshbut = new javax.swing.JButton();
        roomcombo = new javax.swing.JComboBox();
        searchbut = new javax.swing.JButton();
        cancelbut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        completebut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Customer");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("searchuser.png")));
        setIconImages(null);

        buttonGroup1.add(nameradio);
        nameradio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nameradio.setText("Name");
        nameradio.setOpaque(false);

        buttonGroup1.add(cnicradio);
        cnicradio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cnicradio.setText("CNIC");
        cnicradio.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setLabelFor(nameradio);
        jLabel1.setText("Search By:");

        buttonGroup1.add(roomradio);
        roomradio.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        roomradio.setText("Room");
        roomradio.setOpaque(false);

        nametext.setBackground(new java.awt.Color(204, 255, 204));
        nametext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setLabelFor(nametext);
        jLabel2.setText("Name:");

        cnictext.setBackground(new java.awt.Color(204, 255, 204));
        cnictext.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setLabelFor(nametext);
        jLabel3.setText("CNIC:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Room:");

        refreshbut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        refreshbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heavenhostal/refresh.png"))); // NOI18N
        refreshbut.setText("Refresh");

        roomcombo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        searchbut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        searchbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heavenhostal/searchuser.png"))); // NOI18N
        searchbut.setText("Search Record");

        cancelbut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cancelbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heavenhostal/cancel.png"))); // NOI18N
        cancelbut.setText("Cancel");

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "CNIC", "Phone", "Occupation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        completebut.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        completebut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/heavenhostal/data.png"))); // NOI18N
        completebut.setText("Show Complete Record");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(nameradio)
                                .addGap(99, 99, 99)
                                .addComponent(cnicradio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(refreshbut)
                                .addGap(129, 129, 129)
                                .addComponent(roomcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(roomradio)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nametext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                                    .addComponent(cnictext, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(searchbut)
                            .addGap(18, 18, 18)
                            .addComponent(completebut, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cancelbut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameradio)
                            .addComponent(cnicradio)
                            .addComponent(jLabel1))
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(roomradio)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nametext, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cnictext, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(refreshbut)
                    .addComponent(roomcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbut)
                    .addComponent(completebut)
                    .addComponent(cancelbut))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {refreshbut, roomcombo});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public class MyItemHandler implements ItemListener{

        @Override
        public void itemStateChanged(ItemEvent e) {
            if(nameradio.isSelected()){
                nametext.setEnabled(true);
                cnictext.setEnabled(false);
                refreshbut.setEnabled(false);
                roomcombo.setEnabled(false);
                
            }
            if(cnicradio.isSelected()){
                nametext.setEnabled(false);
                cnictext.setEnabled(true);
                refreshbut.setEnabled(false);
                roomcombo.setEnabled(false);
            
            
            }
            if(roomradio.isSelected()){
                nametext.setEnabled(false);
                cnictext.setEnabled(false);
                refreshbut.setEnabled(true);
                roomcombo.setEnabled(true);
            
            }
            
        }
    }
    
    
    
    
    public class MyHandler implements ActionListener{
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        DBConnection dbs = new DBConnection();
        Connection conn = dbs.db();
        @Override
        public void actionPerformed(ActionEvent e) {
            if(e.getActionCommand().equals("Refresh")){
                    
                
                try{
                    Statement stmt = conn.createStatement();
                    ResultSet rs = stmt.executeQuery("select * from rooms");
                    while(rs.next()){
                            if(rs.getString(2).equals("occupied"))
                                roomcombo.addItem(rs.getString(1));
                        }
                    }catch(Exception ex){
                
                            JOptionPane.showMessageDialog(null, "Error Retrieving Room Database", "Error",0);
                }
                refreshbut.setEnabled(false);
            }else if(e.getActionCommand().equals("Search Record")){
                int counter = model.getRowCount();
                
                for(int i =counter-1;i>=0;i-- ){
                    model.removeRow(i);
                }
                
                String search=null;
                String query=null;
                
                if(nameradio.isSelected()){
                    search = nametext.getText();
                    query = "select * from customer where name LIKE '%"+search+"%'";
                }
                if(cnicradio.isSelected()){
                    search = cnictext.getText();
                    query = "select * from customer where cnic LIKE '%"+search+"%'";
                }
                if(roomradio.isSelected()){
                    search = (String)roomcombo.getSelectedItem();
                    query = "select * from rooms where roomlabel LIKE '%"+search+"%'";
                }
                try{
                    Statement stmt = conn.createStatement();
                    ResultSet rs = stmt.executeQuery(query);
                    while(rs.next()){
                        String[] st = new String[4];
                        st[0] = rs.getString(1);
                        st[1] = rs.getString(2);
                        st[2] = rs.getString(3);
                        st[3] = rs.getString(4);
                        model.addRow(st);
                    
                    }
                }catch(Exception ex){
                
                }
            }
                    
                
        }            
            
            }
       
        
    
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelbut;
    private javax.swing.JRadioButton cnicradio;
    private javax.swing.JTextField cnictext;
    private javax.swing.JButton completebut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton nameradio;
    private javax.swing.JTextField nametext;
    private javax.swing.JButton refreshbut;
    private javax.swing.JComboBox roomcombo;
    private javax.swing.JRadioButton roomradio;
    private javax.swing.JButton searchbut;
    // End of variables declaration//GEN-END:variables
}
